from __future__ import annotations

bdt_config = {
    "28May25_baseline": {
        "modelname": "28May25_baseline",
        "hyperpars": {
            "objective": "multi:softprob",
            "max_depth": 9,
            "subsample": 0.3,
            "alpha": 8.0,
            "gamma": 2.0,
            "lambda": 2.0,
            "colsample_bytree": 1.0,
            "num_parallel_tree": 100,
            "eval_metric": "mlogloss",
            "tree_method": "hist",
            "num_class": 8,
            # "device": "cuda",
        },
        "num_rounds": 30,
        "test_size": 0.8,
        "random_seed": 42,
        "train_vars": {
            "fatjet": [
                "ttFatJetPt",
                "ttFatJetPhi",
                "ttFatJetEta",
                "ttFatJetParTmassResApplied",
                "ttFatJetParTmassVisApplied",
                "ttFatJetParTQCD",
                "ttFatJetParTTop",
                "ttFatJetParTQCD0HF",
                "ttFatJetParTQCD1HF",
                "ttFatJetParTQCD2HF",
                "ttFatJetParTTopW",
                "ttFatJetParTTopbW",
                "ttFatJetParTXtauhtauh",
                "ttFatJetParTXtauhtaue",
                "ttFatJetParTXtauhtaum",
                "ttFatJetParTXbb",
            ],
            "misc": ["METPt", "METPhi"],
        },
    },
    "test": {
        "modelname": "test",
        "hyperpars": {
            "objective": "multi:softprob",
            "max_depth": 12,
            "subsample": 0.3,
            "alpha": 8.0,
            "gamma": 2.0,
            "lambda": 2.0,
            "min_child_weight": 0,
            "colsample_bytree": 1.0,
            "num_parallel_tree": 10,
            "eval_metric": "mlogloss",
            "tree_method": "hist",
            "num_class": 8,
            # "device": "cuda",
        },
        "num_rounds": 10,
        "test_size": 0.8,
        "random_seed": 42,
        "train_vars": {
            "fatjet": [
                "ttFatJetPt",
                "ttFatJetPhi",
                "ttFatJetEta",
                "ttFatJetParTmassResApplied",
                "ttFatJetParTmassVisApplied",
                "ttFatJetParTQCD",
                "ttFatJetParTTop",
                "ttFatJetParTQCD0HF",
                "ttFatJetParTQCD1HF",
                "ttFatJetParTQCD2HF",
                "ttFatJetParTTopW",
                "ttFatJetParTTopbW",
                "ttFatJetParTXtauhtauh",
                "ttFatJetParTXtauhtaue",
                "ttFatJetParTXtauhtaum",
                "ttFatJetParTXbb",
            ],
            "misc": ["METPt", "METPhi"],
        },
    },
    "10July25_baseline": {
        "modelname": "10July25_baseline",
        "hyperpars": {
            "objective": "multi:softprob",
            "max_depth": 9,
            "subsample": 0.3,
            "alpha": 8.0,
            "gamma": 2.0,
            "lambda": 2.0,
            "colsample_bytree": 1.0,
            "num_parallel_tree": 100,
            "eval_metric": "mlogloss",
            "tree_method": "hist",
            "num_class": 8,
            # "device": "cuda",
        },
        "num_rounds": 30,
        "test_size": 0.8,
        "random_seed": 42,
        "train_vars": {
            "fatjet": [
                "ttFatJetPt",
                "ttFatJetPhi",
                "ttFatJetEta",
                "ttFatJetParTmassResApplied",
                "ttFatJetParTmassVisApplied",
                "ttFatJetParTQCD",
                "ttFatJetParTTop",
                "ttFatJetParTQCD0HF",
                "ttFatJetParTQCD1HF",
                "ttFatJetParTQCD2HF",
                "ttFatJetParTTopW",
                "ttFatJetParTTopbW",
                "ttFatJetParTXtauhtauh",
                "ttFatJetParTXtauhtaue",
                "ttFatJetParTXtauhtaum",
                "ttFatJetParTXbb",
            ],
            "misc": ["METPt", "METPhi"],
        },
    },
    "10July25_leptons": {
        "modelname": "10July25_leptons",
        "hyperpars": {
            "objective": "multi:softprob",
            "max_depth": 12,
            "subsample": 0.2,
            "alpha": 8.0,
            "gamma": 4.0,
            "lambda": 4.0,
            "colsample_bytree": 1.0,
            "num_parallel_tree": 70,
            "eval_metric": "mlogloss",
            "tree_method": "hist",
            "num_class": 8,
            # "device": "cuda",
        },
        "num_rounds": 50,
        "test_size": 0.2,
        "random_seed": 42,
        "train_vars": {
            "fatjet": [
                "ttFatJetPt",
                "ttFatJetPhi",
                "ttFatJetEta",
                "ttFatJetParTmassResApplied",
                "ttFatJetParTmassVisApplied",
                "ttFatJetParTQCD",
                "ttFatJetParTTop",
                "ttFatJetParTQCD0HF",
                "ttFatJetParTQCD1HF",
                "ttFatJetParTQCD2HF",
                "ttFatJetParTTopW",
                "ttFatJetParTTopbW",
                "ttFatJetParTXtauhtauh",
                "ttFatJetParTXtauhtaue",
                "ttFatJetParTXtauhtaum",
                "ttFatJetParTXbb",
            ],
            "leptons": [
                "ttElectronPt",
                "ttElectronEta",
                "ttElectronPhi",
                "ttElectronMass",
                "ttMuonPt",
                "ttMuonEta",
                "ttMuonPhi",
                "ttMuonMass",
            ],
            "misc": ["METPt", "METPhi", "ht"],
        },
    },
    "13July25_leptons_noXbb": {
        "modelname": "13July25_leptons_noXbb",
        "hyperpars": {
            "objective": "multi:softprob",
            "max_depth": 12,
            "subsample": 0.2,
            "alpha": 8.0,
            "gamma": 4.0,
            "lambda": 4.0,
            "colsample_bytree": 1.0,
            "num_parallel_tree": 70,
            "eval_metric": "mlogloss",
            "tree_method": "hist",
            "num_class": 8,
            # "device": "cuda",
        },
        "num_rounds": 50,
        "test_size": 0.2,
        "random_seed": 42,
        "var_classes": ["fatjet", "leptons", "misc"],
        "train_vars": {
            "fatjet": [
                "ttFatJetPt",
                "ttFatJetPhi",
                "ttFatJetEta",
                "ttFatJetParTmassResApplied",
                "ttFatJetParTmassVisApplied",
                "ttFatJetParTQCD",
                "ttFatJetParTTop",
                "ttFatJetParTQCD0HF",
                "ttFatJetParTQCD1HF",
                "ttFatJetParTQCD2HF",
                "ttFatJetParTTopW",
                "ttFatJetParTTopbW",
                "ttFatJetParTXtauhtauh",
                "ttFatJetParTXtauhtaue",
                "ttFatJetParTXtauhtaum",
            ],
            "leptons": [
                "ttElectronPt",
                "ttElectronEta",
                "ttElectronPhi",
                "ttElectronMass",
                "ttMuonPt",
                "ttMuonEta",
                "ttMuonPhi",
                "ttMuonMass",
            ],
            "misc": ["METPt", "METPhi", "ht"],
        },
    },
    "29July25_loweta_lowreg": {
        "modelname": "29July25_loweta_lowreg",
        "hyperpars": {
            "objective": "multi:softprob",
            "max_depth": 12,
            "eta": 0.07,
            "subsample": 0.2,
            "alpha": 1.0,
            "gamma": 1.0,
            "lambda": 1.0,
            "colsample_bytree": 0.6,
            "num_parallel_tree": 20,
            "eval_metric": "mlogloss",
            "tree_method": "hist",
            "num_class": 8,
            # "device": "cuda",
        },
        "num_rounds": 500,
        "test_size": 0.2,
        "random_seed": 42,
        "var_classes": ["fatjet", "leptons", "misc"],
        "train_vars": {
            "fatjet": [
                "ttFatJetPt",
                "ttFatJetPhi",
                "ttFatJetEta",
                "ttFatJetParTmassResApplied",
                "ttFatJetParTmassVisApplied",
                "ttFatJetParTQCD",
                "ttFatJetParTTop",
                "ttFatJetParTQCD0HF",
                "ttFatJetParTQCD1HF",
                "ttFatJetParTQCD2HF",
                "ttFatJetParTTopW",
                "ttFatJetParTTopbW",
                "ttFatJetParTXtauhtauh",
                "ttFatJetParTXtauhtaue",
                "ttFatJetParTXtauhtaum",
            ],
            "leptons": [
                "ttElectronPt",
                "ttElectronEta",
                "ttElectronPhi",
                "ttElectronMass",
                "ttMuonPt",
                "ttMuonEta",
                "ttMuonPhi",
                "ttMuonMass",
            ],
            "misc": ["METPt", "METPhi", "ht"],
        },
    },
}
