from __future__ import annotations

bdt_config = {
    "28May25_baseline": {
        "modelname": "28May25_baseline",
        "hyperpars": {
            "objective": "multi:softprob",
            "max_depth": 9,
            "subsample": 0.3,
            "alpha": 8.0,
            "gamma": 2.0,
            "lambda": 2.0,
            "colsample_bytree": 1.0,
            "num_parallel_tree": 100,
            "eval_metric": "mlogloss",
            "tree_method": "hist",
            "num_class": 8,
            # "device": "cuda",
        },
        "num_rounds": 30,
        "test_size": 0.8,
        "random_seed": 42,
        "train_vars": {
            "fatjet": {
                "feats": [
                    "ttFatJetPt",
                    "ttFatJetPhi",
                    "ttFatJetEta",
                    "ttFatJetParTmassResApplied",
                    "ttFatJetParTmassVisApplied",
                    "ttFatJetParTQCD",
                    "ttFatJetParTTop",
                    "ttFatJetParTQCD0HF",
                    "ttFatJetParTQCD1HF",
                    "ttFatJetParTQCD2HF",
                    "ttFatJetParTTopW",
                    "ttFatJetParTTopbW",
                    "ttFatJetParTXtauhtauh",
                    "ttFatJetParTXtauhtaue",
                    "ttFatJetParTXtauhtaum",
                    "ttFatJetParTXbb",
                ],
                "len": 3,
            },
            "misc": {
                "feats": ["METPt", "METPhi"],
                "len": 1,
            },
        },
    },
    "test": {
        "modelname": "test",
        "hyperpars": {
            "objective": "multi:softprob",
            "max_depth": 12,
            "subsample": 0.3,
            "alpha": 8.0,
            "gamma": 2.0,
            "lambda": 2.0,
            "min_child_weight": 0,
            "colsample_bytree": 1.0,
            "num_parallel_tree": 10,
            "eval_metric": "mlogloss",
            "tree_method": "hist",
            "num_class": 8,
            # "device": "cuda",
        },
        "num_rounds": 10,
        "test_size": 0.8,
        "random_seed": 42,
        "train_vars": {
            "fatjet": {
                "feats": [
                    "ttFatJetPt",
                    "ttFatJetPhi",
                    "ttFatJetEta",
                    "ttFatJetParTmassResApplied",
                    "ttFatJetParTmassVisApplied",
                    "ttFatJetParTQCD",
                    "ttFatJetParTTop",
                    "ttFatJetParTQCD0HF",
                    "ttFatJetParTQCD1HF",
                    "ttFatJetParTQCD2HF",
                    "ttFatJetParTTopW",
                    "ttFatJetParTTopbW",
                    "ttFatJetParTXtauhtauh",
                    "ttFatJetParTXtauhtaue",
                    "ttFatJetParTXtauhtaum",
                    "ttFatJetParTXbb",
                ],
                "len": 3,
            },
            "misc": {
                "feats": ["METPt", "METPhi"],
                "len": 1,
            },
        },
    },
}
