from __future__ import annotations

bdt_config = {
    "test_fast": {
        "modelname": "test_fast",
        "hyperpars": {
            "objective": "multi:softmax",
            "max_depth": 8,
            # "subsample": 0.3,
            # "alpha": 8.0,
            # "gamma": 2.0,
            # "lambda": 2.0,
            # "min_child_weight": 0,
            # "colsample_bytree": 1.0,
            # "num_parallel_tree": 100,
            "eval_metric": "mlogloss",
            "tree_method": "hist",
            "num_class": 8,
            # "device": "cuda",
        },
        "num_rounds": 20,
        "random_seed": 42,
        "train_vars": {
            "fatjet": {
                "feats": [
                    "ak8FatJetPt",
                    "ak8FatJetPhi",
                    "ak8FatJetEta",
                    "ak8FatJetParTmassResApplied",
                    "ak8FatJetParTmassVisApplied",
                    "ak8FatJetParTQCD",
                    "ak8FatJetParTTop",
                    "ak8FatJetParTQCD0HF",
                    "ak8FatJetParTQCD1HF",
                    "ak8FatJetParTQCD2HF",
                    "ak8FatJetParTTopW",
                    "ak8FatJetParTTopbW",
                    "ak8FatJetParTXtauhtauh",
                    "ak8FatJetParTXtauhtaue",
                    "ak8FatJetParTXtauhtaum",
                    "ak8FatJetParTXbb",
                ],
                "len": 3,
            },
            "misc": {
                "feats": ["METPt", "METPhi"],
                "len": 1,
            },
        },
    },
    "test": {
        "modelname": "test",
        "hyperpars": {
            "objective": "multi:softmax",
            "max_depth": 12,
            "subsample": 0.3,
            "alpha": 8.0,
            "gamma": 2.0,
            "lambda": 2.0,
            "min_child_weight": 0,
            "colsample_bytree": 1.0,
            "num_parallel_tree": 100,
            "eval_metric": "mlogloss",
            "tree_method": "hist",
            "num_class": 8,
            # "device": "cuda",
        },
        "num_rounds": 20,
        "random_seed": 42,
        "train_vars": {
            "fatjet": {
                "feats": [
                    "ak8FatJetPt",
                    "ak8FatJetPhi",
                    "ak8FatJetEta",
                    "ak8FatJetParTmassResApplied",
                    "ak8FatJetParTmassVisApplied",
                    "ak8FatJetParTQCD",
                    "ak8FatJetParTTop",
                    "ak8FatJetParTQCD0HF",
                    "ak8FatJetParTQCD1HF",
                    "ak8FatJetParTQCD2HF",
                    "ak8FatJetParTTopW",
                    "ak8FatJetParTTopbW",
                    "ak8FatJetParTXtauhtauh",
                    "ak8FatJetParTXtauhtaue",
                    "ak8FatJetParTXtauhtaum",
                    "ak8FatJetParTXbb",
                ],
                "len": 3,
            },
            "misc": {
                "feats": ["METPt", "METPhi"],
                "len": 1,
            },
        },
    },
}
